### ISSUE TITLE
Altimeter Driver

### ISSUE THREAD

**Issue by tkindy** [AIAANortheastern/karman-avionics#10]
Develop and test the driver for the TE Connectivity MS560702BA03-50 altimeter

**Comment by tkindy** [comment]
The basic logic is implemented but requires testing on the board.

**Comment by ADKaster** [comment]
Current progress: 
Receiving pressure value that indicates 0.1 bar ...
Calibration values and Temperature return 0
Need to solder headers on board to take advantage of SPI test points.
